### ISSUE TITLE
Branding in browser tab

### ISSUE THREAD

**Issue by sdabhi23** [sdabhi23/frontporch#12]
Change tab name and logo!

Current tab name & logo:
<img width="222" alt="image" src="https://github.com/user-attachments/assets/03de8734-5fdb-4689-87a0-1493604d73b2">

**Comment by Patilritik** [comment]
@sdabhi23 can you please tell what should be the tab name and logo?

**Comment by sdabhi23** [comment]
<img width="82" alt="image" src="https://github.com/user-attachments/assets/823511c3-f7ed-4a90-ac77-af76dc88e9e5">

https://tabler.io/icons/icon/cloud-network

this should be the icon. the tab name could either be set to just `frontporch` or could be dynamic like `frontporch - <page name>` or even just `<page name>`

-----

@Patilritik this issue seems to have been picked up by @mparth14, you can take a look at some other issues in the repo!
